create table why_feit_component
(
    id                bigint generated by default as identity
        primary key,
    annual_stipend    integer,
    application       varchar(255),
    count_description varchar(255),
    count_programs    integer,
    image_url         varchar(255),
    salary            integer,
    title             varchar(255),
    video_url         varchar(255),
    visible           boolean
);

alter table why_feit_component
    owner to postgres;

INSERT INTO public.why_feit_component (id, annual_stipend, application, count_description, count_programs, image_url, salary, title, video_url, visible) VALUES (1, 1200, '96', 'Bakalárskych programov', 6, 'feitImages/usmev.jpg', 1600, 'Prečo študovať na FEIT?', 'https://www.youtube.com/watch?v=k8cmcQF-CNo', true);
