spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


application:
  name: FeitUniza
  security:
    enable: true
    jwt:
      secret-key: "f45666c0d61ee85f12c95767f3c27ae4c08711387ada21ab3ba6828a133dd278"
      expiration: "28800000" # 8 hours in milliseconds
  url:
    base-url: "http://localhost:8080/"
    api-url: "api/v1/"
  image:
    base-url: "images/"
