create table feature_box_component
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    image_url   varchar(255),
    link        varchar(255),
    title       varchar(255),
    visible     boolean
);

alter table feature_box_component
    owner to postgres;

INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (3, 'Automatizácia je fenomén 21. storočia. Urobíme z teba špecialistu v oblasti spoľahlivej a bezpečnej komunikácie, či spracovania informácií pre inteligentnú dopravu a moderný priemysel.', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/AT-O@3x-150x150.png', 'automatizacia', ' Automatizácia 1213', true);
INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (5, 'Rád spájaš výkonovku a programovanie? Nučíš sa pokročilé návrhové techniky elektrických obvodov, rozvodov a sietí. Zoznámiš sa s vysokým napätím, veľkými výkonmi a budeš mať kontrolu nad výrobou a distribúciou obrovskej energie.', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/E-O@3x-300x300.png', 'elektrotechnika', 'Elektrotechnika 123123', true);
INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (6, 'Nielen lekári zachraňujú životy. V našich biomedicínskych a elektrotechnických laboratóriách sa naučíš navrhovať a konštruovať lekárske prístroje a budeš pri vývoji nových medicínskych zariadení.', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/BMI-O@3x-300x300.png', 'biomedicinske-inzinierstvo', 'Biomedicínske inžinierstvo', true);
INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (1, e'Dokážeš spojiť umenie s technikou? Tak naskoč do rozbehnutého vlaku moderných multimédií. Objav svet mobilných aplikácií, webov, 3D priestoru, gamedizajnu a počítačového videnia.
                                ', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/AT-O@3x-150x150.png', 'multimedialne-technologie', 'Multimediálne technológie', true);
INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (4, e'Steve Jobs, Elon Musk a … ty? Získaj vedomosti o najnovších informačno-komunikačných a sieťových technológiách a zmeň spôsob, akým budú ľudia komunikovať.
                                ', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/T-O@3x-300x300.png', 'komunikacne-a-informacne-technologie', 'Komunikačné a informačné technológie', true);
INSERT INTO public.feature_box_component (id, description, image_url, link, title, visible) VALUES (2, 'Optika spôsobila novú technologickú revolúciu nielen v priemysle a prenose dát, ale aj v medicíne a bežnom ľudskom živote. Budúcnosť patrí tebe a svetlu. Tak nezahoď svoju šancu študovať hi-tech v oblasti elektrooptiky.', 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/feitImages/EO-W@4x-300x300.png', 'elektrooptika', 'Elektrooptika f', true);
