create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name     varchar(255) not null,
    password varchar(255) not null,
    role     smallint     not null
        constraint users_role_check
            check ((role >= 0) AND (role <= 1))
);

alter table users
    owner to postgres;

INSERT INTO public.users (id, email, name, password, role) VALUES (1, 'test@test.com', 'test@test.com', '$2a$10$tjypoTl4lXWlVhZLNbhgeetvoL7Tf/an8QOrotCtOkSLApOBdnsiS', 0);
INSERT INTO public.users (id, email, name, password, role) VALUES (2, '123@123.com', 'test@test.com', '$2a$10$mpbwFQxr7qyCHWJtGsp.Wu4/mXXccFQgyjH04/h0aBLF0hB1lEEM2', 0);
