create table why_feit_component
(
    id                bigint generated by default as identity
        primary key,
    annual_stipend    integer,
    application       varchar(255),
    count_description varchar(255),
    count_programs    integer,
    image_url         varchar(2048),
    salary            integer,
    title             varchar(1024),
    video_url         varchar(2048),
    visible           boolean
);

alter table why_feit_component
    owner to postgres;

INSERT INTO public.why_feit_component (id, annual_stipend, application, count_description, count_programs, image_url, salary, title, video_url, visible) VALUES (1, 1200, '96', 'Bakalárskych programov', 132, 'http://localhost:8080/api/v1/images/http://localhost:8080/api/v1/images/2025/05/7d3284dd-cd81-442f-8fc7-c1daf1e98334.jpg', 1300, 'Prečo študovať na FEIT?', 'https://www.youtube.com/watch?v=k8cmcQF-CNo', true);
