create table image
(
    id        bigint generated by default as identity
        primary key,
    file_path varchar(255) not null,
    name      varchar(255) not null,
    type      varchar(255) not null
);

alter table image
    owner to postgres;

INSERT INTO public.image (id, file_path, name, type) VALUES (1, '2025/04/a754d7b3-c060-4be9-9ebb-0522aa82a8b9.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (2, '2025/04/c4465fc6-7ad6-48fa-944e-2a80fc8f72d8.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (3, '2025/04/82879928-15e9-46fe-a9ef-72f624421e6b.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (4, '2025/04/8442bfd4-a40d-4454-9e5f-ab3dc6ed7ee1.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (5, '2025/04/28a6feb6-c10e-4c56-895d-711a860117bd.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (6, '2025/04/f773d52a-beaa-4f58-9b1c-05834fd2b344.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (7, '2025/04/d9b553a6-a718-4b9c-8e96-42a6f7feae00.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (8, '2025/04/c4b6ce3b-d0ca-425f-9374-82cb9cb51245.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (9, '2025/04/5a7f004b-6bb4-4176-93c7-1cfb2dba9b0b.png', 'Download-Icon.png', 'image/png');
INSERT INTO public.image (id, file_path, name, type) VALUES (10, '2025/04/bb8b3aa1-530b-4c16-8f5f-0c16a6914acf.jpg', 'DH 6.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (11, 'feitImages/iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (12, '2025/04/ff8308ce-1e4a-4949-8d61-abdce788f73e.jpeg', 'Scan 1.jpeg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (13, '2025/04/9672c99d-e5c5-4ca9-93f7-7bfb15483e1f.jpg', 'iScreen Shoter - Google Chrome - 250415110849.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (14, '2025/04/fd9b8b61-0cf9-42bc-b8a4-371deb3712a3.jpg', 'iScreen Shoter - Google Chrome - 250415110849.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (15, '2025/04/25a6dbea-fbf3-48d0-b3b1-3dc04cef6240.jpg', 'iScreen Shoter - Google Chrome - 250415111046.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (16, '2025/04/609b34d8-800a-45c9-a2a1-d287d414fa52.jpg', 'iScreen Shoter - Google Chrome - 250415111046.jpg', 'image/jpeg');
