create table image
(
    id        bigint generated by default as identity
        primary key,
    file_path varchar(255) not null,
    name      varchar(255) not null,
    type      varchar(255) not null
);

alter table image
    owner to postgres;

INSERT INTO public.image (id, file_path, name, type) VALUES (3, '2025/03/430424cf-98df-419a-b12f-87f332b58045.jpg', 'iScreen Shoter - Microsoft Teams - 250321205547.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (4, '2025/03/5fc6a437-1094-4d35-b970-0e171d28dbb1.jpg', 'iScreen Shoter - Microsoft Teams - 250321205547.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (5, '2025/03/fca45b29-d2c5-44ea-a457-12dcfd478765.jpg', 'iScreen Shoter - Google Chrome - 250318084242.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (6, '2025/03/50d43416-c1d0-4815-bc9d-ee78f1f3591e.jpg', 'iScreen Shoter - Microsoft Teams - 250321205547.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (7, '2025/03/6a30a190-53ff-4848-8be2-db2b7d23f50b.jpg', 'iScreen Shoter - Microsoft Teams - 250321205547.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (8, '2025/03/fde33750-1a4d-4e8b-9cef-aad5df640f08.jpg', 'iScreen Shoter - Microsoft Teams - 250321205547.jpg', 'image/jpeg');
