create table posts
(
    id             bigint generated by default as identity
        primary key,
    author         varchar(255),
    content        varchar(20000) not null,
    created_at     timestamp,
    main_image_url varchar(255),
    title          varchar(255)   not null
);

alter table posts
    owner to postgres;

INSERT INTO public.posts (id, author, content, created_at, main_image_url, title) VALUES (11, 'admin', '<h2>H1test<br>h1<br><br></h2><img src="http://localhost:8080/api/v1/images/2025/04/609b34d8-800a-45c9-a2a1-d287d414fa52.jpg"><h2><br><br></h2><p></p><hr><p></p><p></p><p></p><p>asdda<br><br></p>', '2025-04-15 11:11:53.589265', 'http://localhost:8080/api/v1/images/2025/04/25a6dbea-fbf3-48d0-b3b1-3dc04cef6240.jpg', 'Hello ');
