create table slider_component
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    label       varchar(255),
    title       varchar(255),
    visible     boolean
);

alter table slider_component
    owner to postgres;

INSERT INTO public.slider_component (id, description, label, title, visible) VALUES (1, 'Okrem kvalitného vzdelania ti ponúkame aj super študentský život. Život, ktorý patrí k nádherným študentským rokom', 'Študentský život', 'Život na FEIT', false);
