create table tags
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint ukt48xdq560gs3gap9g7jg36kgc
            unique
);

alter table tags
    owner to postgres;

INSERT INTO public.tags (id, name) VALUES (1, 'java');
INSERT INTO public.tags (id, name) VALUES (2, 'spring');
INSERT INTO public.tags (id, name) VALUES (3, 'image');
INSERT INTO public.tags (id, name) VALUES (4, 'kokos');
INSERT INTO public.tags (id, name) VALUES (5, 'koko44s');
INSERT INTO public.tags (id, name) VALUES (6, 'koko414s');
INSERT INTO public.tags (id, name) VALUES (7, 'zbran');
INSERT INTO public.tags (id, name) VALUES (8, 'brutalne');
INSERT INTO public.tags (id, name) VALUES (9, 'feit');
