create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name     varchar(255) not null,
    password varchar(255) not null,
    role     smallint     not null
        constraint users_role_check
            check ((role >= 0) AND (role <= 1))
);

alter table users
    owner to postgres;

INSERT INTO public.users (id, email, name, password, role) VALUES (1, 'test@test.com', 'test', '$2a$10$uuSztr7XQ95A0nzYlJJsLetLDPPFDJV/kgc/QYkZYMdQv/c488sni', 1);
INSERT INTO public.users (id, email, name, password, role) VALUES (2, 'test@test1.com', 'test1', 'password', 1);
