create table image
(
    id        bigint generated by default as identity
        primary key,
    file_path varchar(255) not null,
    name      varchar(255) not null,
    type      varchar(255) not null
);

alter table image
    owner to postgres;

INSERT INTO public.image (id, file_path, name, type) VALUES (1, '2025/04/a754d7b3-c060-4be9-9ebb-0522aa82a8b9.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (2, '2025/04/c4465fc6-7ad6-48fa-944e-2a80fc8f72d8.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (3, '2025/04/82879928-15e9-46fe-a9ef-72f624421e6b.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (4, '2025/04/8442bfd4-a40d-4454-9e5f-ab3dc6ed7ee1.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (5, '2025/04/28a6feb6-c10e-4c56-895d-711a860117bd.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (6, '2025/04/f773d52a-beaa-4f58-9b1c-05834fd2b344.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (7, '2025/04/d9b553a6-a718-4b9c-8e96-42a6f7feae00.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (8, '2025/04/c4b6ce3b-d0ca-425f-9374-82cb9cb51245.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (9, '2025/04/5a7f004b-6bb4-4176-93c7-1cfb2dba9b0b.png', 'Download-Icon.png', 'image/png');
INSERT INTO public.image (id, file_path, name, type) VALUES (10, '2025/04/bb8b3aa1-530b-4c16-8f5f-0c16a6914acf.jpg', 'DH 6.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (11, 'feitImages/iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'iScreen Shoter - IntelliJ IDEA - 250328122120.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (12, '2025/04/ff8308ce-1e4a-4949-8d61-abdce788f73e.jpeg', 'Scan 1.jpeg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (13, '2025/04/9672c99d-e5c5-4ca9-93f7-7bfb15483e1f.jpg', 'iScreen Shoter - Google Chrome - 250415110849.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (14, '2025/04/fd9b8b61-0cf9-42bc-b8a4-371deb3712a3.jpg', 'iScreen Shoter - Google Chrome - 250415110849.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (15, '2025/04/25a6dbea-fbf3-48d0-b3b1-3dc04cef6240.jpg', 'iScreen Shoter - Google Chrome - 250415111046.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (16, '2025/04/609b34d8-800a-45c9-a2a1-d287d414fa52.jpg', 'iScreen Shoter - Google Chrome - 250415111046.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (17, '2025/05/cc0a7308-fd6b-4a28-b0aa-94b3e7a3a2c2.jpeg', 'Scan.jpeg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (18, '2025/05/7d3284dd-cd81-442f-8fc7-c1daf1e98334.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (19, '2025/05/e311171b-e8a6-4276-b89d-ded1f00aa3a0.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (20, '2025/05/d0824c84-0677-4261-bb72-86559a8da3e8.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (21, '2025/05/74fc7995-c011-49a9-9beb-ccd4c68169a9.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (22, '2025/05/543019f4-e2cf-4385-b864-237b6618f4ef.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (23, '2025/05/1c9eb62d-5203-4dde-976f-d175a1d0f41a.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (24, '2025/05/efdab18c-b0ed-412c-b03e-2cc00a01cfd8.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (25, '2025/05/ac35c0f2-1edf-42f8-bfdd-e87138855604.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (26, '2025/05/b5c0213e-9b7a-4dd3-86d7-9a3b240c10ea.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (27, '2025/05/61d229b1-7a15-4821-9116-a0321c7e5df2.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (28, '2025/05/e9a13c0d-da28-4ed2-b56a-34aae02c3276.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (29, '2025/05/ca3f94ba-60d3-4eaf-ba51-3b83ecf9b6c7.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (30, '2025/05/edd526ea-9aca-4559-a543-d12ed043c1b3.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (31, '2025/05/2d0e88d7-0cd4-4e59-82fe-5ca3e38a4073.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (32, '2025/05/84e08a48-5099-4888-876a-1c28b26325df.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (33, '2025/05/91f1b736-a36d-4d49-957a-45fcb4dc68b2.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (34, '2025/05/87c56b5a-7732-42c1-a4a5-cd435aa872e4.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (35, '2025/05/d5b178a7-3412-4f31-99b8-1f58a876aca2.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (36, '2025/05/a9449116-d4fb-46d0-a7ba-81394bde8660.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (37, 'feitImages/b24f9cc9-d3af-4a8f-b635-99950580acdc.jpg', 'usmev.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (38, '2025/06/5f14f636-32b2-4f59-a32e-7a1344a24ba9.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (39, '2025/06/00031b37-c9d4-4c57-bec8-6dd2ce54d962.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (40, '2025/06/21671cef-8b77-45d5-ad71-e3b115463130.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (41, '2025/06/d1e4ba63-8d83-4060-a49a-089ef75e53c6.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (42, '2025/06/74a5b787-6761-4a96-a714-396b7562456c.png', 'image-3.png', 'image/png');
INSERT INTO public.image (id, file_path, name, type) VALUES (43, '2025/06/c330978b-55ca-40c0-b848-97308cf35a6e.png', 'image-3.png', 'image/png');
INSERT INTO public.image (id, file_path, name, type) VALUES (44, '2025/06/32443ae2-5276-46ea-83dc-4437a5be4a40.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (45, 'feitImages/f690b7e6-09ba-41b7-863e-c7d9a3621401.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (46, 'feitImages/36f03e37-b3f0-4d71-947e-0d673df22ef2.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (47, 'feitImages/48b0024b-2e3e-4f20-9b36-2c546c141ac1.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (48, 'feitImages/2ce8b578-a394-4b6f-91d8-2df08b857f7a.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (49, 'feitImages/6e7901f9-17e4-4a33-b3b8-f64bdd3499a7.jpg', 'svos-2025-photo-scaled.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (50, 'feitImages/80132c80-1392-4dad-9bff-4bdff01e9ef6.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (51, 'feitImages/a1d99f75-364f-4ce3-adaf-fa1fe7743d9d.jpg', 'uniza_zmens.jpg', 'image/jpeg');
INSERT INTO public.image (id, file_path, name, type) VALUES (52, 'feitImages/73fb89ca-b249-4573-8907-1ae165f5903c.png', 'image-3.png', 'image/png');
INSERT INTO public.image (id, file_path, name, type) VALUES (53, '2025/06/1dbed2f3-1b78-49b9-a728-9a4aff4e2e85.jpg', 'uniza_zmens.jpg', 'image/jpeg');
