create table logo_item
(
    id                bigint not null
        primary key,
    alt               varchar(255),
    image_url         varchar(255),
    logo_component_id bigint
        constraint fkqgb44t08bwhxj8p3qwby2sd8w
            references logo_component
);

alter table logo_item
    owner to postgres;

INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (1, null, 'feitImages/loga/logo-goodrequest.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (2, null, 'feitImages/loga/logo-sse-180x92.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (3, null, 'feitImages/loga/SystemHouse_Solutions_logo_stående_PMS.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (4, null, 'feitImages/loga/Brainit-RGB-Black.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (5, null, 'feitImages/loga/logo-rtvs-140x87.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (6, null, 'feitImages/loga/logo-nxp-180x71.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (7, null, 'feitImages/loga/logo-GlobalLogic-210x53.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (8, null, 'feitImages/loga/ch-logo.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (9, null, 'feitImages/loga/logo-emtest-190x61.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (10, null, 'feitImages/loga/logo-evpu-210x91.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (11, null, 'feitImages/loga/logo-zaIT-170x85.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (12, null, 'feitImages/loga/logo-onsemi-255x90.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (13, null, 'feitImages/loga/logo-betamont-255x33.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (14, null, 'feitImages/loga/logo-seps-160x108.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (15, null, 'feitImages/loga/logo-orange-100x100.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (16, null, 'feitImages/loga/logo-bel-255x64.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (17, null, 'feitImages/loga/logo-tvRaj-115x115.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (18, null, 'feitImages/loga/logo-continental-255x46.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (19, null, 'feitImages/loga/logo-tes-200x39.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (20, null, 'feitImages/loga/logo-siemens.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (21, null, 'feitImages/loga/g832-280x60.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (22, null, 'feitImages/loga/deltech-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (23, null, 'feitImages/loga/logo_rgb-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (24, null, 'feitImages/loga/SSD_logo-198x98.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (25, null, 'feitImages/loga/Schaeffler_green_cmyk.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (26, null, 'feitImages/loga/m2m.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (36, null, 'feitImages/loga/logo-goodrequest.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (37, null, 'feitImages/loga/logo-sse-180x92.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (38, null, 'feitImages/loga/SystemHouse_Solutions_logo_stående_PMS.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (39, null, 'feitImages/loga/Brainit-RGB-Black.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (40, null, 'feitImages/loga/logo-rtvs-140x87.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (41, null, 'feitImages/loga/logo-nxp-180x71.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (42, null, 'feitImages/loga/logo-GlobalLogic-210x53.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (43, null, 'feitImages/loga/ch-logo.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (44, null, 'feitImages/loga/logo-emtest-190x61.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (45, null, 'feitImages/loga/logo-evpu-210x91.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (46, null, 'feitImages/loga/logo-zaIT-170x85.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (47, null, 'feitImages/loga/logo-onsemi-255x90.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (48, null, 'feitImages/loga/logo-betamont-255x33.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (49, null, 'feitImages/loga/logo-seps-160x108.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (50, null, 'feitImages/loga/logo-orange-100x100.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (51, null, 'feitImages/loga/logo-bel-255x64.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (52, null, 'feitImages/loga/logo-tvRaj-115x115.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (53, null, 'feitImages/loga/logo-continental-255x46.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (54, null, 'feitImages/loga/logo-tes-200x39.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (55, null, 'feitImages/loga/logo-siemens.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (56, null, 'feitImages/loga/g832-280x60.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (57, null, 'feitImages/loga/deltech-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (58, null, 'feitImages/loga/logo_rgb-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (59, null, 'feitImages/loga/SSD_logo-198x98.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (60, null, 'feitImages/loga/Schaeffler_green_cmyk.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (61, null, 'feitImages/loga/m2m.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (62, 'uniza_zmens', 'feitImages/80132c80-1392-4dad-9bff-4bdff01e9ef6.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (90, null, 'feitImages/loga/logo-goodrequest.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (91, null, 'feitImages/loga/logo-sse-180x92.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (92, null, 'feitImages/loga/SystemHouse_Solutions_logo_stående_PMS.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (93, null, 'feitImages/loga/Brainit-RGB-Black.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (94, null, 'feitImages/loga/logo-rtvs-140x87.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (95, null, 'feitImages/loga/logo-nxp-180x71.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (96, null, 'feitImages/loga/logo-GlobalLogic-210x53.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (97, null, 'feitImages/loga/ch-logo.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (98, null, 'feitImages/loga/logo-emtest-190x61.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (99, null, 'feitImages/loga/logo-evpu-210x91.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (100, null, 'feitImages/loga/logo-zaIT-170x85.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (101, null, 'feitImages/loga/logo-onsemi-255x90.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (102, null, 'feitImages/loga/logo-betamont-255x33.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (103, null, 'feitImages/loga/logo-seps-160x108.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (104, null, 'feitImages/loga/logo-orange-100x100.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (63, null, 'feitImages/loga/logo-goodrequest.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (64, null, 'feitImages/loga/logo-sse-180x92.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (65, null, 'feitImages/loga/SystemHouse_Solutions_logo_stående_PMS.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (66, null, 'feitImages/loga/Brainit-RGB-Black.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (67, null, 'feitImages/loga/logo-rtvs-140x87.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (68, null, 'feitImages/loga/logo-nxp-180x71.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (69, null, 'feitImages/loga/logo-GlobalLogic-210x53.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (70, null, 'feitImages/loga/ch-logo.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (71, null, 'feitImages/loga/logo-emtest-190x61.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (72, null, 'feitImages/loga/logo-evpu-210x91.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (73, null, 'feitImages/loga/logo-zaIT-170x85.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (74, null, 'feitImages/loga/logo-onsemi-255x90.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (75, null, 'feitImages/loga/logo-betamont-255x33.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (76, null, 'feitImages/loga/logo-seps-160x108.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (77, null, 'feitImages/loga/logo-orange-100x100.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (78, null, 'feitImages/loga/logo-bel-255x64.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (79, null, 'feitImages/loga/logo-tvRaj-115x115.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (80, null, 'feitImages/loga/logo-continental-255x46.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (81, null, 'feitImages/loga/logo-tes-200x39.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (82, null, 'feitImages/loga/logo-siemens.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (83, null, 'feitImages/loga/g832-280x60.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (84, null, 'feitImages/loga/deltech-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (85, null, 'feitImages/loga/logo_rgb-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (86, null, 'feitImages/loga/SSD_logo-198x98.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (87, null, 'feitImages/loga/Schaeffler_green_cmyk.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (88, null, 'feitImages/loga/m2m.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (89, null, 'feitImages/80132c80-1392-4dad-9bff-4bdff01e9ef6.jpg', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (105, null, 'feitImages/loga/logo-bel-255x64.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (106, null, 'feitImages/loga/logo-tvRaj-115x115.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (107, null, 'feitImages/loga/logo-continental-255x46.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (108, null, 'feitImages/loga/logo-tes-200x39.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (109, null, 'feitImages/loga/logo-siemens.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (110, null, 'feitImages/loga/g832-280x60.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (111, null, 'feitImages/loga/deltech-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (112, null, 'feitImages/loga/logo_rgb-1.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (113, null, 'feitImages/loga/SSD_logo-198x98.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (114, null, 'feitImages/loga/Schaeffler_green_cmyk.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (115, null, 'feitImages/loga/m2m.png', null);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (116, null, 'feitImages/loga/logo-goodrequest.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (117, null, 'feitImages/loga/logo-sse-180x92.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (118, null, 'feitImages/loga/SystemHouse_Solutions_logo_stående_PMS.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (119, null, 'feitImages/loga/Brainit-RGB-Black.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (120, null, 'feitImages/loga/logo-rtvs-140x87.jpg', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (121, null, 'feitImages/loga/logo-nxp-180x71.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (122, null, 'feitImages/loga/logo-GlobalLogic-210x53.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (123, null, 'feitImages/loga/ch-logo.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (124, null, 'feitImages/loga/logo-emtest-190x61.jpg', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (125, null, 'feitImages/loga/logo-evpu-210x91.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (126, null, 'feitImages/loga/logo-zaIT-170x85.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (127, null, 'feitImages/loga/logo-onsemi-255x90.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (128, null, 'feitImages/loga/logo-betamont-255x33.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (129, null, 'feitImages/loga/logo-seps-160x108.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (130, null, 'feitImages/loga/logo-orange-100x100.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (131, null, 'feitImages/loga/logo-bel-255x64.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (132, null, 'feitImages/loga/logo-tvRaj-115x115.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (133, null, 'feitImages/loga/logo-continental-255x46.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (134, null, 'feitImages/loga/logo-tes-200x39.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (135, null, 'feitImages/loga/logo-siemens.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (136, null, 'feitImages/loga/g832-280x60.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (137, null, 'feitImages/loga/deltech-1.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (138, null, 'feitImages/loga/logo_rgb-1.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (139, null, 'feitImages/loga/SSD_logo-198x98.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (140, null, 'feitImages/loga/Schaeffler_green_cmyk.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (141, null, 'feitImages/loga/m2m.png', 1);
INSERT INTO public.logo_item (id, alt, image_url, logo_component_id) VALUES (142, 'uniza_zmens', 'feitImages/a1d99f75-364f-4ce3-adaf-fa1fe7743d9d.jpg', 1);
