create table settings
(
    id                   bigint generated by default as identity
        primary key,
    enabled_registration boolean not null
);

alter table settings
    owner to postgres;

INSERT INTO public.settings (id, enabled_registration) VALUES (1, false);
