create table tags
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint ukt48xdq560gs3gap9g7jg36kgc
            unique
);

alter table tags
    owner to postgres;

INSERT INTO public.tags (id, name) VALUES (9, 'tag1');
INSERT INTO public.tags (id, name) VALUES (10, 'tag2');
INSERT INTO public.tags (id, name) VALUES (11, '12312');
INSERT INTO public.tags (id, name) VALUES (12, '123123');
INSERT INTO public.tags (id, name) VALUES (13, '123');
INSERT INTO public.tags (id, name) VALUES (1, 'Novinky vo FEITcity');
INSERT INTO public.tags (id, name) VALUES (2, 'Podávanie prihlášok');
INSERT INTO public.tags (id, name) VALUES (3, 'Udalosti');
INSERT INTO public.tags (id, name) VALUES (4, 'Nezaradené');
INSERT INTO public.tags (id, name) VALUES (5, '1');
INSERT INTO public.tags (id, name) VALUES (6, '2');
