create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name     varchar(255) not null
        constraint uk3g1j96g94xpk3lpxl2qbl985x
            unique,
    password varchar(255) not null,
    role     smallint     not null
        constraint users_role_check
            check ((role >= 0) AND (role <= 1))
);

alter table users
    owner to postgres;

INSERT INTO public.users (id, email, name, password, role) VALUES (1, '1@1.com', '1', '$2a$10$VIDRLnpNUy6vDBdIkY5fge.D9dgVX4eiZ2VKHWypURVEj8RJYVnAu', 0);
INSERT INTO public.users (id, email, name, password, role) VALUES (3, '2@2.sk', '2', '$2a$10$NNAxFXcA5K9XQzBG50BnFer7IZaQyW3RcK/hjHFaxJuibNN0J60fi', 0);
INSERT INTO public.users (id, email, name, password, role) VALUES (4, '3@3.com', '3', '$2a$10$KruUDGoSMA/6iIU3kRJUPejGVKScyn65HiLYdldsLHMG1Ia/SsY9e', 0);
INSERT INTO public.users (id, email, name, password, role) VALUES (5, 'teswt@test.com', 'tes213t', '$2a$10$xIHkRUdKhn6rsrEipNZWFeoyp6m0MaCNpK.XMK9AfPJvCBOlgmikO', 0);
